name: 🚀 Node.js CI / CD PIPELINE name
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '12.x'
      - run: npm install
      - run: npm run start &
      - name: "Call API"
        uses: indiesdev/curl@v1.1
        id: api
        with:
          # The target URL
          # Required: true if custom-config is not set
          url: http://localhost:3000
          method: "GET"
          log-response: true
          run: echo ${{ steps.api.outputs.data }}
